/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package juegos;

/**
 *
 * @author WAX
 */
public class Juegos extends javax.swing.JFrame {

    /**
     * Creates new form juegos
     */
    public Juegos() {
        initComponents();
        inicial();
    }
    public void inicial(){
        GMenu.add(RAhorcado);
        GMenu.add(RNumero);
        GMenu.add(RSalir);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        GMenu = new javax.swing.ButtonGroup();
        RNumero = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        RAhorcado = new javax.swing.JRadioButton();
        RSalir = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Juegos");
        setResizable(false);

        RNumero.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        RNumero.setText("Adivina el número");
        RNumero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RNumeroActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        jLabel1.setText("Elija el juego:");

        RAhorcado.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        RAhorcado.setText("Ahorcado");
        RAhorcado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RAhorcadoActionPerformed(evt);
            }
        });

        RSalir.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        RSalir.setText("Salir");
        RSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(RAhorcado)
                            .addComponent(RNumero)
                            .addComponent(RSalir))))
                .addContainerGap(79, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel1)
                .addGap(37, 37, 37)
                .addComponent(RNumero)
                .addGap(18, 18, 18)
                .addComponent(RAhorcado)
                .addGap(18, 18, 18)
                .addComponent(RSalir)
                .addContainerGap(64, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void RNumeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RNumeroActionPerformed
        Ahorcado ah=new Ahorcado();
        ah.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_RNumeroActionPerformed

    private void RAhorcadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RAhorcadoActionPerformed
        Numero num=new Numero();
        num.setVisible(true);
        this.setVisible(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_RAhorcadoActionPerformed

    private void RSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_RSalirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Juegos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Juegos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Juegos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Juegos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Juegos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup GMenu;
    private javax.swing.JRadioButton RAhorcado;
    private javax.swing.JRadioButton RNumero;
    private javax.swing.JRadioButton RSalir;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
