/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package menu;

/**
 *
 * @author WAX
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
                iniciar();
    }

    public void iniciar(){
        BGOpciones.add(RFactorial);
        BGOpciones.add(RFibonacci);
        BGOpciones.add(RMinmax);
        BGOpciones.add(RSalir);
        LEntrada1.setVisible(false);
        LEntrada2.setVisible(false);
        TFEntrada1.setVisible(false);
        TFEntrada2.setVisible(false);
        TResultado.setVisible(false);
        BProcesar.setVisible(false);
        TFEntrada1.setText("");
        TFEntrada2.setText("");
        LTitulo.setText("");
        TResultado.setText("");
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BGOpciones = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        TResultado = new javax.swing.JTextArea();
        BProcesar = new javax.swing.JButton();
        RFibonacci = new javax.swing.JRadioButton();
        RFactorial = new javax.swing.JRadioButton();
        RMinmax = new javax.swing.JRadioButton();
        RSalir = new javax.swing.JRadioButton();
        TFEntrada1 = new javax.swing.JTextField();
        TFEntrada2 = new javax.swing.JTextField();
        LEntrada1 = new javax.swing.JLabel();
        LEntrada2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        LTitulo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        TResultado.setColumns(20);
        TResultado.setRows(5);
        jScrollPane1.setViewportView(TResultado);

        BProcesar.setText("Procesar");
        BProcesar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BProcesarActionPerformed(evt);
            }
        });

        RFibonacci.setText("Fibonacci");
        RFibonacci.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RFibonacciMouseClicked(evt);
            }
        });

        RFactorial.setText("Factorial");
        RFactorial.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RFactorialMouseClicked(evt);
            }
        });

        RMinmax.setText("Min-Max");
        RMinmax.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RMinmaxMouseClicked(evt);
            }
        });

        RSalir.setText("Salir");
        RSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RSalirMouseClicked(evt);
            }
        });

        jLabel1.setText("Elija una opción:");

        LTitulo.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(2, 2, 2)
                                    .addComponent(jLabel1))
                                .addComponent(RSalir, javax.swing.GroupLayout.Alignment.LEADING))
                            .addComponent(RMinmax)
                            .addComponent(RFibonacci)
                            .addComponent(RFactorial))
                        .addGap(63, 63, 63)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(LEntrada2, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)
                                    .addComponent(LEntrada1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(TFEntrada2, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(TFEntrada1, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(125, 125, 125))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(LTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(BProcesar)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(LTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LEntrada1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TFEntrada1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(TFEntrada2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LEntrada2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BProcesar)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(RFactorial)
                        .addGap(33, 33, 33)
                        .addComponent(RFibonacci)
                        .addGap(32, 32, 32)
                        .addComponent(RMinmax)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(RSalir))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void RSalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RSalirMouseClicked
        System.exit(0);
    }//GEN-LAST:event_RSalirMouseClicked

    private void RFactorialMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RFactorialMouseClicked
        iniciar();
        LTitulo.setText("Determina el número factorial");
        LEntrada1.setVisible(true);
        TFEntrada1.setVisible(true);
        TResultado.setVisible(true);
        BProcesar.setVisible(true);
        LEntrada1.setText("Número:");
        
    }//GEN-LAST:event_RFactorialMouseClicked

    private void RFibonacciMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RFibonacciMouseClicked
                iniciar();
        LTitulo.setText("Exhibe la serie fibonacci");
        TFEntrada1.setVisible(true);
        LEntrada1.setVisible(true);
        TResultado.setVisible(true);
        BProcesar.setVisible(true);
        LEntrada1.setText("Número:");
    }//GEN-LAST:event_RFibonacciMouseClicked

    private void RMinmaxMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RMinmaxMouseClicked
               iniciar();
        LTitulo.setText("Proporciona la serie de números indicados");
        TFEntrada1.setVisible(true);
        TFEntrada2.setVisible(true);
        LEntrada1.setVisible(true);
        LEntrada2.setVisible(true);
        TResultado.setVisible(true);
        BProcesar.setVisible(true);
        LEntrada1.setText("Número mínimo:");
        LEntrada2.setText("Número máximo:");
    }//GEN-LAST:event_RMinmaxMouseClicked
    private int factorial(int num){
        if(num>0){
            return num*factorial(num-1);  
        }else return 1;
    }
int fibonacci(int n)
{
    if (n>1){
       return fibonacci(n-1) + fibonacci(n-2);  
    }
    else if (n==1) { 
        return 1;
    }
    else if (n==0){  
        return 0;
    }
    else{ 
        TResultado.setText("Debes ingresar un tamaño mayor o igual a 1");
        return -1; 
    }
}
    private void BProcesarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BProcesarActionPerformed
        
           
             TResultado.setText("");
        if(RFactorial.isSelected()){
            int num1=Integer.valueOf(TFEntrada1.getText());
           TResultado.setText("El factorial de "+num1+" es "+String.valueOf(factorial(num1)));
            
        }
        if(RFibonacci.isSelected()){
            String acumulador="";
            int num1=Integer.valueOf(TFEntrada1.getText());
            for (int i = 0; i < num1; i++) {
               acumulador+=String.valueOf(fibonacci(i))+" ";      
            }
           TResultado.setText("La serie fibonacci para el "+num1+"avo elemento es:\n "+acumulador);
            
        }
        if(RMinmax.isSelected()){
            int num1=Integer.valueOf(TFEntrada1.getText());
            int num2=Integer.valueOf(TFEntrada2.getText());
            String resultado="";
            for (int i = num1; i < num2+1; i++) {
                resultado+=String.valueOf(i)+" ";
                
            }
           TResultado.setText("El resultado es "+resultado);
            
        }
    }//GEN-LAST:event_BProcesarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup BGOpciones;
    private javax.swing.JButton BProcesar;
    private javax.swing.JLabel LEntrada1;
    private javax.swing.JLabel LEntrada2;
    private javax.swing.JLabel LTitulo;
    private javax.swing.JRadioButton RFactorial;
    private javax.swing.JRadioButton RFibonacci;
    private javax.swing.JRadioButton RMinmax;
    private javax.swing.JRadioButton RSalir;
    private javax.swing.JTextField TFEntrada1;
    private javax.swing.JTextField TFEntrada2;
    private javax.swing.JTextArea TResultado;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
